### ISSUE TITLE
App crashes in column view if album double clicked

### ISSUE THREAD

**Issue by jeremypw** [elementary/music#91]
To reproduce:

* Start app in icon-view
* Switch to column-view (right-most mode button) - starts displaying all albums
* Single-click on a album - displays album contents.
* Double-click on the same album - crash with message ERROR:arraylist.c:967:gee_array_list_real_get: assertion failed: (index < _size).

Back-trace:
---------------
```
(gdb) bt
#0  0x00007ffff43cc428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff43ce02a in __GI_abort () at abort.c:89
#2  0x00007ffff4d4cd65 in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4d4cdfa in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7109ca9 in ?? () from /usr/lib/x86_64-linux-gnu/libgee-0.8.so.2
#5  0x00007ffff4795490 in noise_playlist_get (self=0xada2c0, index=0) at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/core/Playlists/Playlist.vala:67
#6  0x0000000000442912 in noise_playback_manager_media_from_current_index (self=0xc161d0, index_in_current=0)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/PlaybackManager.vala:177
#7  0x00000000004b7467 in noise_view_wrapper_play_first_media (self=0xc98b70, force=0x7fffffffc1dc)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/Views/Wrappers/ViewWrapper.vala:282
#8  0x00000000004d9681 in noise_column_browser_column_row_activated (self=0x184e700)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/Views/ListView/ColumnBrowser/ColumnBrowser.vala:234
#9  0x00000000004d9221 in _noise_column_browser_column_row_activated_noise_browser_column_row_activated (_sender=0x1bd57a0, text=0x1dcb760 "20th Century", self=0x184e700)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/Views/ListView/ColumnBrowser/ColumnBrowser.vala:212
#10 0x00007ffff5000a5a in g_cclosure_marshal_VOID__STRINGv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff4ffe1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff50189a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff501908f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00000000004d7256 in noise_browser_column_view_double_click (self=0x1bd57a0, path=0x1941640, column=0x19f1c40)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/Views/ListView/ColumnBrowser/BrowserColumn.vala:307
#15 0x00000000004d5787 in _noise_browser_column_view_double_click_gtk_tree_view_row_activated (_sender=0x1bdbb60, path=0x1941640, column=0x19f1c40, self=0x1bd57a0)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/Views/ListView/ColumnBrowser/BrowserColumn.vala:154
#16 0x00007ffff4ffdfa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff500ffc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff5018d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff501908f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff6776f46 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007fffedcdde40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#22 0x00007fffedcdd8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#23 0x00007ffff4ffecf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff4ffe1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff50189a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff501908f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff6604c16 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff5000dbe in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff4ffe1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff50189a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff501908f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff6601bab in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff66031ab in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff6605de5 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff65d5beb in gtk_event_controller_handle_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff6786bfb in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff664b09a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff4ffe1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff50184b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff501908f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007ffff6788c3c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff66483be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007ffff664a1bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007ffff61b7d92 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#45 0x00007ffff4d27197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff4d273f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#47 0x00007ffff4d2749c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff6e14d6d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#49 0x000000000042f95d in _vala_main (args=0x7fffffffde48, args_length1=1) at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/main.vala:49
#50 0x000000000042f9e6 in main (argc=1, argv=0x7fffffffde48) at /media/jeremy/Shared/shared_data/Vala/Elementary/music-branches/music/src/main.vala:29
```

**Comment by Bat41** [comment]
In fact, you this also occurs when you double click on an artist. And you don't even have to single click it before to reproduce.

**Comment by o-alquimista** [comment]
![peek 2018-03-13 11-31](https://user-images.githubusercontent.com/25424263/37349432-2d365fea-26b5-11e8-8e03-08f5f6317fe9.gif)

**Comment by leonardo-lemos** [comment]
I can't reproduce this problem with master.

**Comment by jeremypw** [comment]
Still happening for me.

**Comment by kgrubb** [comment]
@jeremypw, does this still happen for you? I'm unable to reproduce anymore. I believe the issue has been resolved! :tada:

**Comment by jeremypw** [comment]
Yeah, seems fixed -thanks.
